Put in safety hooks to avoid accidently running Swarm services as root. Includes changes to the startup scripts and a new swarm.*.runasuser administrative parameter.

diff --git a/adm/run-gdplogd b/adm/run-gdplogd
--- a/adm/run-gdplogd
+++ b/adm/run-gdplogd
@@ -1,5 +1,11 @@
 #!/bin/sh
 
+if [ `whoami` = "root" ]
+then
+	echo "$0: cannot run as root (FATAL)"
+	exit 1;
+fi
+
 export HOME=`echo ~gdp`
 cd $HOME
 
diff --git a/adm/start-gdp b/adm/start-gdp
--- a/adm/start-gdp
+++ b/adm/start-gdp
@@ -1,4 +1,10 @@
 #!/bin/sh 
+if [ `whoami` = "root" ]
+then
+	echo "$0: cannot run as root (FATAL)"
+	exit 1;
+fi
+
 export HOME=`echo ~gdp`
 cd $HOME
 
